### PR TITLE
Work in progress re-architecture

### PR DESCRIPTION
**Pull request by parndt**
This is to provide a nice diff comparison but is not ready to merge yet.

### CODE REVIEW

**Comment by parndt** [comment]
Seems ready?
If so, :shipit:

**Comment by parndt** [comment]
@knewter @saturnflyer @robyurkowski first though, I definitely think we need to have another discussion around our interactors or recent lack thereof.

**Comment by robyurkowski** [comment]
Since it's unlikely we'll all be in a room together sometime soon, what are you thinking, @parndt?

**Comment by parndt** [comment]
Well, I am not sure that I want to completely kill interactors but I am going to merge this.

We can re-evaluate how those should be added back and whether we should use DCI approaches for doing so.

**Pull request merged**
