### PR TITLE
Demonstrate form submission.

### PR DESCRIPTION
**Pull request by robyurkowski**
Not quite ready to merge, but the starting points.

### CODE REVIEW

**Comment by knewter** [comment]
I didn't add a test :-\

**Comment by robyurkowski** [comment]
~~Thou art a gentleman and a scholar.~~ WAT

**Comment by knewter** [comment]
incoming

**Comment by knewter** [comment]
pow!

**Comment by parndt** [comment]
How can we be sure that the code even works if there is no test that was written before the functionality? ;-)

**Pull request merged**
