### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by knewter**
There's no license.  I don't know what license is planned but I figure this is an easy enough way to force the discussion :heart:

### CODE REVIEW

**Comment by parndt** [comment]
@robyurkowski and I were looking into licenses last night.. Eclipse public license actually looks fairly decent. This needs to be discussed more though!

**Comment by robyurkowski** [comment]
Really, EPL? It's all the freedom of MIT or BSD-3clause with three times the text.

My own personal pref is [BSD 3clause](http://opensource.org/licenses/BSD-3-Clause), because it's like the MIT, just with non-endorsement and in bullet form.

**Comment by parndt** [comment]
:trollface:

**Comment by robyurkowski** [comment]
Oh, you.

**Comment by robyurkowski** [comment]
Okay, by executive fiat, BSD 3-clause it is. Let me know of any objections in principle.

**Pull request closed without merging**
