### PR TITLE
How should an Image entity work?

### PR DESCRIPTION
**Pull request by parndt**

### CODE REVIEW

**Comment by parndt** [comment]
I am not sure what, exactly, an Image looks like conceptually? What's the minimum for it to be usable?

**Comment by GeekOnCoffee** [comment]
So what an image requires will depend to some degree on what image library is being used.... 

Things which will almost certainly be required: 
Filename / Path

Things which might be required: 
Dimensions
Orientation
Visible/Hidden

If you're wanting to store images externally (S3, etc) there's a whole different set of requirements...

**Comment by parndt** [comment]
Yeah, seems legit. I think that part of what's getting to me is whether visible/hidden are domain specific things that are enforced further up somehow? I just don't know how to structure that stuff. 

Do you want to take a look at the branch to see whether you could flesh out the Image entity a little more? I agree that filename is required and we could probably build the relative / absolute URL from it.. what do you think?

**Comment by knewter** [comment]
I would think that we probably want something just like 'url' and 'dimensions' at first.  If we wanted an "Image with Caption" then that seems like a class that either derives from or composes this one (likely the latter) right?  Same for Image With Title (and that definitely makes me think composition is better, because "Image With Caption And Title" should be composable with one of those atop the other

**Comment by parndt** [comment]
I like your ideas.. May I subscribe to your newsletter good sir?

**Comment by johanb** [comment]
Should an Image not just be a "Resource" with mime-type image and dimensions ?

**Comment by GeekOnCoffee** [comment]
Resource is an icky generic term. 
Companies refer to staff, conference rooms, automobiles, etc all as resources.

I could see calling them Assets, although that's almost as icky... 

Video is a good thing to keep in mind when making this more abstract...

**Comment by parndt** [comment]
What about Media of type Displayable?

**Comment by johanb** [comment]
:+1: on Media.

**Comment by parndt** [comment]
What should we do?

**Comment by knewter** [comment]
Maybe start out with a Media controller in the backend and a Media entity, appropriately subclassed?  I figure a decent (and approachable) start would be to build a backend way to manage Assets (or Media, or whatever they're called).  This is somewhat normal in a CMS no?

**Pull request closed without merging**
